language: python
python:
  - "3.4"
install:
  - sudo apt-get update
  - wget http://repo.continuum.io/miniconda/Miniconda3-3.4.2-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  #- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION actuariat_test
  #- conda install -r requirements.txt
  - conda install Cython
  - conda install Flask
  - conda install Jinja2
  - conda install Markdown
  - conda install MarkupSafe
  - conda install PyYAML
  - conda install Pygments
  - conda install Sphinx
  - conda install Werkzeug
  - conda install XlsxWriter
  - conda install coverage
  - conda install ipython
  - conda install jsonschema
  - conda install lxml
  - conda install matplotlib
  - conda install numpy
  - conda install openpyxl
  - conda install pandas
  - conda install pycparser
  - conda install pyparsing
  - conda install pytz
  - conda install pyzmq
  - conda install requests
  - conda install six
  - conda install virtualenv
  - conda install mccabe
  - conda install pep8
  - conda install feedparser
  - conda install cvxopt
  - conda install scipy
  - conda install h5py
  - conda install networkx
  #- source activate test-environment
  - pip install -r requirements.txt
  - pip install -r requirements_ext.txt
  - python setup.py install
script:
  - python setup.py unittests
