environment:

  global:
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_compiler.cmd"

  matrix:

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%\\python -m pip install --upgrade pip"
  - "%PYTHON%\\Scripts\\pip install pymyinstall"
  - "%PYTHON%\\Scripts\\pymy_install3 pylzma shapely pyproj cartopy"
  - "%PYTHON%\\Scripts\\pip install -r requirements_conda.txt"
  - "%PYTHON%\\Scripts\\pip install -r requirements.txt"
  - "%PYTHON%\\Scripts\\pip install -U git+https://github.com/sdpython/pyPdf --no-deps"
  - "%PYTHON%\\Scripts\\pip install tools"
  - "%PYTHON%\\Scripts\\pymy_install3 --task=tool --source=zip graphviz"
  # - "%PYTHON%\\Scripts\\pip install csharpy pythonnet"
  - "dir C:\\projects\\ensae-teaching-cs\\build\\update_modules\\Graphviz\\bin"
  - "set PATH=%PATH%;C:\\projects\\ensae-teaching-cs\\build\\update_modules\\Graphviz\\bin"
  - set PYTHONPATH=src
  - "%PYTHON%\\Scripts\\pip freeze"

build: off

test_script:
  # The job is cut after an hour. Only a subset of unit test is run.
  - "%PYTHON%\\python -u setup.py unittests -d 20 -g \".*((LONG)|(SKIP)|(session9)).*\""

after_test:
  - "%PYTHON%\\python -u setup.py bdist_wheel"

artifacts:
  - path: dist
    name: ensae_teaching_cs

cache:
  # Use the appveyor cache to avoid re-downloading large archives such
  # the MKL numpy and scipy wheels mirrored on a rackspace cloud
  # container, speed up the appveyor jobs and reduce bandwidth.
  # Tips taken from scikit-learn.
  - '%APPDATA%\pip\Cache'
