image:
  - Visual Studio 2019
environment:
  matrix:
    - PYTHON: "C:\\Python310-x64"
      PYTHON_VERSION: "3.10.x"
      PYTHON_ARCH: "64"
init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%\\python -m pip install --upgrade pip"
  - pip install wheel
  # for many packages
  - "%PYTHON%\\Scripts\\pip install -r requirements-win.txt"
  # install precompiled versions not available on pypi
  - "%PYTHON%\\Scripts\\pymy_install3 shapely pyproj"
  - "%PYTHON%\\Scripts\\pip install http://www.xavierdupre.fr/enseignement/setup/Cartopy-0.20.1-cp39-cp39-win_amd64.whl"
  - "%PYTHON%\\Scripts\\pymy_install3 cartopy fiona gdal"
  # - "%PYTHON%\\Scripts\\pymy_install3 cartopy"
  # other dependencies
  - "%PYTHON%\\Scripts\\pip install -r requirements.txt --no-deps"
  - set PYTHONPATH=src

build: off

cache:
  # Use the appveyor cache to avoid re-downloading large archives such
  # the MKL numpy and scipy wheels mirrored on a rackspace cloud
  # container, speed up the appveyor jobs and reduce bandwidth.
  # Tips taken from scikit-learn.
  - '%APPDATA%\pip\Cache'

test_script:
  # The job is cut after an hour. Only a subset of unit test is run.
  - "%PYTHON%\\python -u setup.py unittests -d 20 -g \".*((LONG)|(SKIP)|(session9)).*\""

after_test:
  - "%PYTHON%\\python -u setup.py bdist_wheel"

artifacts:
  - path: dist
    name: ensae_teaching_cs
